import { Patient, DoctorPrescription, SessionHistory, BCIIntentEvent, AppointmentBooking } from '../src/types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'NP-101',
    name: 'Marcus Vance',
    age: 42,
    gender: 'Male',
    diagnosis: 'Amyotrophic Lateral Sclerosis (ALS) - Bulbar Onset',
    paralysisType: 'Locked-in Syndrome / Flaccid Quadriplegia',
    injuryLevel: 'Upper & Lower Motor Neuron Degeneration',
    clinicalStage: 'ALSFRS-R Score: 11/48 (Severe motor loss, intact cognition)',
    mobilityStatus: 'Zero voluntary limb movement; preserved eye vertical saccades',
    bciParadigm: 'P300 Matrix Speller + Mu Rhythm Motor Imagery',
    currentDoctor: 'Dr. Riley Chen, MD, PhD (Chief Neurotechnologist)',
    roomBed: 'Neuro-ICU Bay 4A',
    status: 'stable',
    signalQuality: 96,
    attentionScore: 84,
    focusScore: 78,
    fatigueScore: 24,
    activeChannelCount: 16,
    samplingRate: 256,
    dominantWave: 'Alpha',
    bandPowers: {
      alpha: 38,
      beta: 22,
      theta: 24,
      delta: 16,
      mu: 28,
    },
    motorImageryAccuracy: 92.4,
    currentIntent: {
      command: "Select letter 'E' (P300 Speller matrix)",
      confidence: 0.94,
      timestamp: 'Just now',
      channelTrigger: 'Cz, Pz (P300 latency 312ms)',
    },
    eegConfig: {
      baselineAlpha: 36,
      baselineBeta: 20,
      baselineTheta: 25,
      baselineDelta: 19,
      muSuppressionThreshold: 0.42,
      filterNotch: true,
      filterBandpass: '0.5 - 40 Hz',
      impedanceCheck: {
        Fp1: 2.1, Fp2: 2.3, F3: 3.0, F4: 2.8, C3: 1.8, C4: 1.9,
        P3: 2.4, P4: 2.2, O1: 1.7, O2: 1.6, T3: 3.5, T4: 3.2,
        Fz: 2.0, Cz: 1.5, Pz: 1.8, Oz: 1.9
      }
    },
    daysInProgram: 24,
  },
  {
    id: 'NP-102',
    name: 'Elena Rostova',
    age: 29,
    gender: 'Female',
    diagnosis: 'Traumatic Spinal Cord Injury (C5 Complete ASIA-A)',
    paralysisType: 'Complete Tetraplegia (C5 Sensorimotor Level)',
    injuryLevel: 'C5 Cervical Vertebral Fracture / Spinal Cord Contusion',
    clinicalStage: 'Post-stabilization Rehab Month 4 · ASIA Impairment Scale A',
    mobilityStatus: 'Paralysis of all 4 limbs and trunk; intact shoulder shrugging & weak bicep',
    bciParadigm: 'Sensorimotor Rhythm (SMR) Hand Grasp Neurofeedback + FES',
    currentDoctor: 'Dr. Sarah Jenkins, MD (Neuro-Rehabilitation Lead)',
    roomBed: 'Rehab Pavilion Room 208',
    status: 'active',
    signalQuality: 93,
    attentionScore: 91,
    focusScore: 86,
    fatigueScore: 19,
    activeChannelCount: 16,
    samplingRate: 256,
    dominantWave: 'Beta',
    bandPowers: {
      alpha: 28,
      beta: 34,
      theta: 22,
      delta: 16,
      mu: 45,
    },
    motorImageryAccuracy: 88.7,
    currentIntent: {
      command: 'Right Hand Grasp Neuro-prosthetic trigger (ERD active)',
      confidence: 0.91,
      timestamp: '1 min ago',
      channelTrigger: 'C3 (Mu suppression -52%)',
    },
    eegConfig: {
      baselineAlpha: 26,
      baselineBeta: 32,
      baselineTheta: 24,
      baselineDelta: 18,
      muSuppressionThreshold: 0.48,
      filterNotch: true,
      filterBandpass: '1.0 - 45 Hz',
      impedanceCheck: {
        Fp1: 2.8, Fp2: 2.6, F3: 2.4, F4: 2.5, C3: 1.4, C4: 1.6,
        P3: 2.1, P4: 2.0, O1: 2.2, O2: 2.1, T3: 3.8, T4: 3.6,
        Fz: 2.2, Cz: 1.8, Pz: 2.0, Oz: 2.3
      }
    },
    daysInProgram: 42,
  },
  {
    id: 'NP-103',
    name: 'David Kim',
    age: 64,
    gender: 'Male',
    diagnosis: 'Ischemic Stroke (Left MCA territory infarction)',
    paralysisType: 'Right Dense Hemiplegia & Expressive Dysphasia',
    injuryLevel: 'Internal Capsule & Primary Motor Cortex (Brodmann Area 4)',
    clinicalStage: 'Subacute Stroke Recovery Day 38 · NIHSS: 14',
    mobilityStatus: 'Right flaccid upper & lower extremity paralysis, facial droop',
    bciParadigm: 'Contralateral Motor Cortex Neuroplasticity Training',
    currentDoctor: 'Dr. Aris Thorne, MD (Vascular Neurologist)',
    roomBed: 'Stroke Recovery Unit Bed 12',
    status: 'recalibrating',
    signalQuality: 89,
    attentionScore: 72,
    focusScore: 68,
    fatigueScore: 41,
    activeChannelCount: 16,
    samplingRate: 256,
    dominantWave: 'Theta',
    bandPowers: {
      alpha: 22,
      beta: 18,
      theta: 38,
      delta: 22,
      mu: 24,
    },
    motorImageryAccuracy: 82.5,
    currentIntent: {
      command: 'Left robotic arm reaching assistance request',
      confidence: 0.85,
      timestamp: '3 mins ago',
      channelTrigger: 'C4 (Right hemispheric compensation)',
    },
    eegConfig: {
      baselineAlpha: 20,
      baselineBeta: 17,
      baselineTheta: 40,
      baselineDelta: 23,
      muSuppressionThreshold: 0.38,
      filterNotch: true,
      filterBandpass: '0.5 - 35 Hz',
      impedanceCheck: {
        Fp1: 3.2, Fp2: 3.1, F3: 2.9, F4: 2.7, C3: 2.2, C4: 1.9,
        P3: 3.0, P4: 2.8, O1: 2.5, O2: 2.4, T3: 4.1, T4: 3.9,
        Fz: 2.6, Cz: 2.1, Pz: 2.4, Oz: 2.7
      }
    },
    daysInProgram: 18,
  },
  {
    id: 'NP-104',
    name: 'Priya Sharma',
    age: 38,
    gender: 'Female',
    diagnosis: 'Guillain-Barré Syndrome (Acute Motor Axonal Neuropathy)',
    paralysisType: 'Acute Severe Flaccid Tetraparesis & Ventilator Dependency',
    injuryLevel: 'Peripheral Motor Nerve Demyelination / Axonopathy',
    clinicalStage: 'Plateau Phase · Hughes Disability Score: Grade 5',
    mobilityStatus: 'Bedbound, minimal neck flexion, communicating via eye gaze',
    bciParadigm: 'Steady-State Visual Evoked Potential (SSVEP) Binary Speller',
    currentDoctor: 'Dr. Riley Chen, MD, PhD (Chief Neurotechnologist)',
    roomBed: 'Neuro-ICU Bay 2B',
    status: 'resting',
    signalQuality: 97,
    attentionScore: 79,
    focusScore: 74,
    fatigueScore: 32,
    activeChannelCount: 16,
    samplingRate: 256,
    dominantWave: 'Alpha',
    bandPowers: {
      alpha: 42,
      beta: 16,
      theta: 26,
      delta: 16,
      mu: 19,
    },
    motorImageryAccuracy: 94.1,
    currentIntent: {
      command: 'Emergency Call Nurse ("Assistance Needed")',
      confidence: 0.98,
      timestamp: '12 mins ago',
      channelTrigger: 'O1, O2 (12 Hz SSVEP resonance peak)',
    },
    eegConfig: {
      baselineAlpha: 40,
      baselineBeta: 15,
      baselineTheta: 28,
      baselineDelta: 17,
      muSuppressionThreshold: 0.35,
      filterNotch: true,
      filterBandpass: '1.0 - 50 Hz',
      impedanceCheck: {
        Fp1: 1.9, Fp2: 1.8, F3: 2.1, F4: 2.0, C3: 1.6, C4: 1.7,
        P3: 1.8, P4: 1.7, O1: 1.3, O2: 1.4, T3: 2.9, T4: 2.8,
        Fz: 1.7, Cz: 1.5, Pz: 1.6, Oz: 1.4
      }
    },
    daysInProgram: 14,
  }
];

export const INITIAL_PRESCRIPTIONS: DoctorPrescription[] = [
  {
    id: 'RX-NP101-01',
    patientId: 'NP-101',
    doctorName: 'Dr. Riley Chen, MD, PhD',
    doctorSpecialty: 'Lead Neurologist & Neurotechnologist',
    licenseNumber: 'MD-CAL-88914-NEU',
    hospitalAffiliation: 'Center for Brain-Computer Rehabilitation & Advanced Neurology',
    datePrescribed: '2026-09-10',
    nextReviewDate: '2026-09-24',
    medications: [
      {
        name: 'Riluzole',
        dosage: '50 mg',
        frequency: 'Every 12 hours (BID)',
        route: 'Oral suspension (via PEG feeding tube)',
        purpose: 'Glutamate neurotoxicity reduction to preserve remaining bulbar & spinal motor neurons',
        startDate: '2026-08-15'
      },
      {
        name: 'Baclofen',
        dosage: '10 mg',
        frequency: 'Three times daily (TID)',
        route: 'Oral (tube)',
        purpose: 'Spasticity reduction and painful spasms alleviation',
        startDate: '2026-08-20'
      },
      {
        name: 'Glycopyrrolate',
        dosage: '1 mg',
        frequency: 'Twice daily as needed',
        route: 'Oral / Sublingual',
        purpose: 'Bulbar secretion management for airway comfort during BCI cap placement',
        startDate: '2026-09-02'
      }
    ],
    bciTherapyProtocol: {
      dailyDurationMinutes: 45,
      sessionFrequency: 'Twice daily: Morning (10:00 AM) & Afternoon (3:00 PM)',
      targetParadigm: 'High-speed P300 Visual Matrix Speller (6x6 characters) + Emergency Nurse Beacon',
      targetBands: 'Pz/Cz P300 component latency window 280-360ms; Mu rhythm 9-11 Hz baseline check',
      classificationThreshold: 0.72,
      assistiveDeviceIntegration: 'Direct interface to bedside AAC Speech Synthesizer and Nurse Call Gateway',
      sensorimotorFocus: 'Mental spelling verification with minimum 8 flashes per character to prevent ocular fatigue',
      neuroplasticityGoal: 'Maintain cognitive engagement, establish 15 words/min communication rate with 90%+ confidence'
    },
    clinicalNotes: 'Marcus shows excellent P300 signal discrimination during morning hours. Fatigue increases sharply after 40 minutes of continuous matrix flashing; limit training blocks to 15-minute segments with 5-minute dark-screen resting intervals. Ensure electrode Cz impedance remains under 3.0 kΩ.',
    warningPrecautions: [
      'Stop BCI session immediately if heart rate exceeds 110 bpm or if autonomic dysreflexia symptoms occur',
      'Do not administer sedative hypnotics within 4 hours prior to BCI communication sessions',
      'Maintain head and neck ergonomic foam stabilizer during 16-channel cap montage'
    ],
    signatureHash: 'eeg-sha256:d8a9f0291e982c730248a8bbf3710928dca9',
    status: 'active'
  },
  {
    id: 'RX-NP102-01',
    patientId: 'NP-102',
    doctorName: 'Dr. Sarah Jenkins, MD',
    doctorSpecialty: 'Director of Spinal Cord Injury Rehabilitation',
    licenseNumber: 'MD-CAL-67120-SCI',
    hospitalAffiliation: 'Spinal Neuro-Restoration & Prosthetics Institute',
    datePrescribed: '2026-09-08',
    nextReviewDate: '2026-09-22',
    medications: [
      {
        name: 'Gabapentin',
        dosage: '300 mg',
        frequency: 'Three times daily (TID)',
        route: 'Oral capsule',
        purpose: 'Central neuropathic pain management following C5 injury',
        startDate: '2026-07-28'
      },
      {
        name: 'Baclofen',
        dosage: '20 mg',
        frequency: 'Twice daily (BID)',
        route: 'Oral tablet',
        purpose: 'Lower extremity and trunk extensor spasticity inhibition',
        startDate: '2026-08-01'
      }
    ],
    bciTherapyProtocol: {
      dailyDurationMinutes: 60,
      sessionFrequency: 'Daily session at 11:30 AM (Post-morning physical therapy)',
      targetParadigm: 'Sensorimotor Rhythm (SMR) Hand Grasp Neurofeedback coupled with bilateral FES orthosis',
      targetBands: 'C3 (Left Motor Cortex) and C4 (Right Motor Cortex) Mu rhythm (10-12 Hz) ERD > 45%',
      classificationThreshold: 0.78,
      assistiveDeviceIntegration: 'Bionic Myoelectric Hand Exoskeleton + FES forearm stimulation array',
      sensorimotorFocus: 'Kinesthetic motor imagery of bilateral power grip and key pinch',
      neuroplasticityGoal: 'Promote cortical reorganization and strengthen corticospinal tract pathway connections'
    },
    clinicalNotes: 'Elena demonstrates rapid learning with sensorimotor rhythm suppression. When imagining right-hand grasp, C3 Mu power drops by 52%, cleanly triggering the robotic hand closing mechanism. Continue daily calibration prior to session.',
    warningPrecautions: [
      'Inspect skin under FES gel electrodes post-session to prevent cutaneous irritation',
      'Verify battery and wireless telemetry connection to hand orthosis before active imagery trials'
    ],
    signatureHash: 'eeg-sha256:71f84091a92e109dcb421a88b20914902a7b',
    status: 'active'
  },
  {
    id: 'RX-NP103-01',
    patientId: 'NP-103',
    doctorName: 'Dr. Aris Thorne, MD',
    doctorSpecialty: 'Vascular Neurologist & Stroke Therapeutics',
    licenseNumber: 'MD-CAL-55204-STR',
    hospitalAffiliation: 'Comprehensive Stroke & Brain Attack Center',
    datePrescribed: '2026-09-12',
    nextReviewDate: '2026-09-26',
    medications: [
      {
        name: 'Aspirin',
        dosage: '81 mg',
        frequency: 'Once daily in the morning',
        route: 'Oral tablet',
        purpose: 'Secondary stroke prevention (Antiplatelet)',
        startDate: '2026-08-10'
      },
      {
        name: 'Atorvastatin',
        dosage: '40 mg',
        frequency: 'Once daily at bedtime (QHS)',
        route: 'Oral tablet',
        purpose: 'Plaque stabilization and lipid control',
        startDate: '2026-08-10'
      },
      {
        name: 'Citicoline',
        dosage: '500 mg',
        frequency: 'Twice daily',
        route: 'Oral tablet',
        purpose: 'Neuronal membrane stabilization and neuroplasticity priming',
        startDate: '2026-08-15'
      }
    ],
    bciTherapyProtocol: {
      dailyDurationMinutes: 30,
      sessionFrequency: 'Twice daily (09:00 AM & 02:00 PM)',
      targetParadigm: 'Contralateral Motor Cortex Neuroplasticity Priming with Virtual Reality Visual Feedback',
      targetBands: 'C3/C4 Theta/Beta ratio normalization; Beta rebound (18-24 Hz) post-movement imagery',
      classificationThreshold: 0.68,
      assistiveDeviceIntegration: 'VR Avatar Mirror Therapy System + Upper-limb robotic rehabilitation gantry',
      sensorimotorFocus: 'Re-activating left perilesional motor circuits via mental practice of right arm extension',
      neuroplasticityGoal: 'Reclaim motor intention coherence and downregulate perilesional slow-wave Theta bursts'
    },
    clinicalNotes: 'Perilesional slow-wave theta activity in left hemisphere is slowly declining compared to initial scans. Keep sessions at 30 minutes maximum to avoid post-stroke cognitive exhaustion. Encourage mental rehearsal with VR mirror arm.',
    warningPrecautions: [
      'Monitor blood pressure before and after BCI trial; abort if systolic > 170 mmHg',
      'Assess for signs of visual fatigue or dizziness during immersive VR feedback'
    ],
    signatureHash: 'eeg-sha256:39ba0182fc610e28bbd9124401829377481c',
    status: 'active'
  },
  {
    id: 'RX-NP104-01',
    patientId: 'NP-104',
    doctorName: 'Dr. Riley Chen, MD, PhD',
    doctorSpecialty: 'Lead Neurologist & Neurotechnologist',
    licenseNumber: 'MD-CAL-88914-NEU',
    hospitalAffiliation: 'Center for Brain-Computer Rehabilitation & Advanced Neurology',
    datePrescribed: '2026-09-14',
    nextReviewDate: '2026-09-28',
    medications: [
      {
        name: 'Intravenous Immunoglobulin (IVIG)',
        dosage: '0.4 g/kg/day',
        frequency: '5-day cycle completed, on bi-weekly maintenance',
        route: 'Intravenous infusion',
        purpose: 'Autoantibody neutralization in acute inflammatory demyelinating polyneuropathy',
        startDate: '2026-09-01'
      },
      {
        name: 'Pregabalin',
        dosage: '75 mg',
        frequency: 'Twice daily (BID)',
        route: 'Oral / Enteral',
        purpose: 'Peripheral nerve dysesthesia and allodynia relief',
        startDate: '2026-09-05'
      }
    ],
    bciTherapyProtocol: {
      dailyDurationMinutes: 25,
      sessionFrequency: 'Three times daily in 15-minute micro-sessions (10:00 AM, 01:30 PM, 06:00 PM)',
      targetParadigm: 'Steady-State Visual Evoked Potential (SSVEP) Dual-Frequency Binary Communicator',
      targetBands: 'Occipital O1/O2 12 Hz and 15 Hz spectral peak amplitude SNR > 6 dB',
      classificationThreshold: 0.85,
      assistiveDeviceIntegration: 'ICU Patient Bedside Display with quick-action tiles: Yes / No / Suction / Family / Pain',
      sensorimotorFocus: 'Visual fixation on 12 Hz flickering target for Affirmation, 15 Hz target for Negative',
      neuroplasticityGoal: 'Provide effortless, fatigue-resistant communication lifeline during paralysis recovery phase'
    },
    clinicalNotes: 'Priya has 100% cognitive preservation with severe motor block. SSVEP provides instant communication with near zero motor strain. Electrodes O1 and Oz must have impedance under 2.0 kΩ for optimal harmonic peak detection.',
    warningPrecautions: [
      'Ensure flickering stimulus brightness is adjusted to ambient ICU lighting to prevent ocular irritation',
      'Coordinate BCI sessions with respiratory therapy schedule'
    ],
    signatureHash: 'eeg-sha256:92cb5514ee0192837bc90184817dca819280',
    status: 'active'
  }
];

export const INITIAL_SESSION_HISTORIES: SessionHistory[] = [
  // Marcus Vance (NP-101) - 6 recent chronological sessions
  {
    id: 'HIST-NP101-01',
    patientId: 'NP-101',
    sessionNumber: 24,
    date: '2026-09-16',
    time: '09:42 AM',
    durationMinutes: 45,
    dominantWave: 'Alpha',
    avgAlpha: 38.4,
    avgBeta: 22.1,
    avgTheta: 23.5,
    avgDelta: 16.0,
    bciAccuracy: 93.8,
    trialsCount: 120,
    successfulCommands: 112,
    fatigueIndex: 24,
    focusScore: 82,
    coherenceScore: 91,
    notes: 'P300 Speller achieved 18 words/minute. Marcus successfully typed full message to family without typographical errors.',
    doctorAssessment: 'Exceptional signal coherence. Latency jitter reduced to 14ms across Cz/Pz.',
    prescribedProtocolAdherence: 100,
  },
  {
    id: 'HIST-NP101-02',
    patientId: 'NP-101',
    sessionNumber: 23,
    date: '2026-09-15',
    time: '10:15 AM',
    durationMinutes: 45,
    dominantWave: 'Alpha',
    avgAlpha: 37.1,
    avgBeta: 21.8,
    avgTheta: 24.2,
    avgDelta: 16.9,
    bciAccuracy: 91.5,
    trialsCount: 115,
    successfulCommands: 105,
    fatigueIndex: 28,
    focusScore: 79,
    coherenceScore: 88,
    notes: 'Nurse call system tested 4 times; 100% detection with average latency 1.4 seconds.',
    doctorAssessment: 'Stable baseline. P300 amplitude maintained at 8.2 µV.',
    prescribedProtocolAdherence: 100,
  },
  {
    id: 'HIST-NP101-03',
    patientId: 'NP-101',
    sessionNumber: 22,
    date: '2026-09-14',
    time: '09:50 AM',
    durationMinutes: 40,
    dominantWave: 'Alpha',
    avgAlpha: 35.8,
    avgBeta: 23.0,
    avgTheta: 25.1,
    avgDelta: 16.1,
    bciAccuracy: 89.2,
    trialsCount: 110,
    successfulCommands: 98,
    fatigueIndex: 33,
    focusScore: 76,
    coherenceScore: 86,
    notes: 'Slight muscle twitch artifact in T3/T4 during minute 28; automatic rejection filter handled cleanly.',
    doctorAssessment: 'Advised 5 min extra rest interval between matrix spelling runs.',
    prescribedProtocolAdherence: 95,
  },
  {
    id: 'HIST-NP101-04',
    patientId: 'NP-101',
    sessionNumber: 21,
    date: '2026-09-13',
    time: '10:30 AM',
    durationMinutes: 45,
    dominantWave: 'Alpha',
    avgAlpha: 36.4,
    avgBeta: 21.0,
    avgTheta: 24.8,
    avgDelta: 17.8,
    bciAccuracy: 88.0,
    trialsCount: 108,
    successfulCommands: 95,
    fatigueIndex: 35,
    focusScore: 74,
    coherenceScore: 84,
    notes: 'Completed spelling of clinical status update and preferred room temperature.',
    doctorAssessment: 'Consistent alpha wave rhythm indicates calm, focused mental state.',
    prescribedProtocolAdherence: 100,
  },
  {
    id: 'HIST-NP101-05',
    patientId: 'NP-101',
    sessionNumber: 20,
    date: '2026-09-12',
    time: '09:40 AM',
    durationMinutes: 42,
    dominantWave: 'Alpha',
    avgAlpha: 34.2,
    avgBeta: 22.4,
    avgTheta: 26.0,
    avgDelta: 17.4,
    bciAccuracy: 86.4,
    trialsCount: 105,
    successfulCommands: 91,
    fatigueIndex: 39,
    focusScore: 71,
    coherenceScore: 82,
    notes: 'Re-calibrated P300 flash sequence to 125ms intervals. Improved user comfort.',
    doctorAssessment: 'Adjustment approved. Threshold lowered slightly to 0.70.',
    prescribedProtocolAdherence: 98,
  },
  {
    id: 'HIST-NP101-06',
    patientId: 'NP-101',
    sessionNumber: 19,
    date: '2026-09-11',
    time: '10:00 AM',
    durationMinutes: 45,
    dominantWave: 'Alpha',
    avgAlpha: 33.8,
    avgBeta: 20.6,
    avgTheta: 27.2,
    avgDelta: 18.4,
    bciAccuracy: 84.7,
    trialsCount: 100,
    successfulCommands: 85,
    fatigueIndex: 42,
    focusScore: 68,
    coherenceScore: 80,
    notes: 'Initial introduction to expanded 36-character communication matrix.',
    doctorAssessment: 'Good baseline comprehension. Progression curve on target.',
    prescribedProtocolAdherence: 92,
  },

  // Elena Rostova (NP-102)
  {
    id: 'HIST-NP102-01',
    patientId: 'NP-102',
    sessionNumber: 42,
    date: '2026-09-16',
    time: '11:35 AM',
    durationMinutes: 60,
    dominantWave: 'Beta',
    avgAlpha: 28.2,
    avgBeta: 34.6,
    avgTheta: 21.8,
    avgDelta: 15.4,
    bciAccuracy: 90.2,
    trialsCount: 85,
    successfulCommands: 77,
    fatigueIndex: 21,
    focusScore: 88,
    coherenceScore: 89,
    notes: 'Right hand grasp imagery triggered robotic exoskeleton with 91% precision. Held target water bottle for 12 seconds.',
    doctorAssessment: 'Sensory-motor rhythm ERD reaches -54% on C3. Significant neuroplastic adaptation.',
    prescribedProtocolAdherence: 100,
  },
  {
    id: 'HIST-NP102-02',
    patientId: 'NP-102',
    sessionNumber: 41,
    date: '2026-09-15',
    time: '11:30 AM',
    durationMinutes: 58,
    dominantWave: 'Beta',
    avgAlpha: 27.5,
    avgBeta: 33.8,
    avgTheta: 22.4,
    avgDelta: 16.3,
    bciAccuracy: 88.5,
    trialsCount: 82,
    successfulCommands: 73,
    fatigueIndex: 25,
    focusScore: 85,
    coherenceScore: 87,
    notes: 'Key pinch motor imagery tested with FES array on thenar muscles.',
    doctorAssessment: 'Mu band desynchronization latency reduced to 240ms.',
    prescribedProtocolAdherence: 100,
  },
  {
    id: 'HIST-NP102-03',
    patientId: 'NP-102',
    sessionNumber: 40,
    date: '2026-09-14',
    time: '11:45 AM',
    durationMinutes: 55,
    dominantWave: 'Beta',
    avgAlpha: 26.9,
    avgBeta: 32.7,
    avgTheta: 23.6,
    avgDelta: 16.8,
    bciAccuracy: 86.8,
    trialsCount: 78,
    successfulCommands: 68,
    fatigueIndex: 30,
    focusScore: 82,
    coherenceScore: 85,
    notes: 'Bilateral hand grasp alternations. Right side significantly stronger signal than left.',
    doctorAssessment: 'Matches C5 asymmetric lesion profile. Continue focusing on dominant right hand.',
    prescribedProtocolAdherence: 95,
  },

  // David Kim (NP-103)
  {
    id: 'HIST-NP103-01',
    patientId: 'NP-103',
    sessionNumber: 18,
    date: '2026-09-16',
    time: '09:10 AM',
    durationMinutes: 30,
    dominantWave: 'Theta',
    avgAlpha: 22.4,
    avgBeta: 18.2,
    avgTheta: 37.8,
    avgDelta: 21.6,
    bciAccuracy: 83.3,
    trialsCount: 60,
    successfulCommands: 50,
    fatigueIndex: 40,
    focusScore: 70,
    coherenceScore: 76,
    notes: 'VR mirror arm extension exercise. Patient successfully completed 50 virtual reach trials with left hemisphere priming.',
    doctorAssessment: 'Gradual downregulation of perilesional delta/theta slow waves. Positive neuroplastic trend.',
    prescribedProtocolAdherence: 100,
  },
  {
    id: 'HIST-NP103-02',
    patientId: 'NP-103',
    sessionNumber: 17,
    date: '2026-09-15',
    time: '09:05 AM',
    durationMinutes: 30,
    dominantWave: 'Theta',
    avgAlpha: 21.8,
    avgBeta: 17.5,
    avgTheta: 39.1,
    avgDelta: 21.6,
    bciAccuracy: 81.6,
    trialsCount: 58,
    successfulCommands: 47,
    fatigueIndex: 44,
    focusScore: 66,
    coherenceScore: 73,
    notes: 'Patient reported feeling mental fatigue around trial 45. Short 2-minute meditation break provided.',
    doctorAssessment: 'Adhering to strict 30-minute limit. Blood pressure remained stable (134/82).',
    prescribedProtocolAdherence: 95,
  },

  // Priya Sharma (NP-104)
  {
    id: 'HIST-NP104-01',
    patientId: 'NP-104',
    sessionNumber: 14,
    date: '2026-09-16',
    time: '10:05 AM',
    durationMinutes: 20,
    dominantWave: 'Alpha',
    avgAlpha: 42.6,
    avgBeta: 15.8,
    avgTheta: 25.4,
    avgDelta: 16.2,
    bciAccuracy: 95.0,
    trialsCount: 40,
    successfulCommands: 38,
    fatigueIndex: 18,
    focusScore: 84,
    coherenceScore: 94,
    notes: 'Dual SSVEP target selection: 12Hz (Yes) vs 15Hz (No). 38/40 trials decoded accurately in <1.2 seconds.',
    doctorAssessment: 'Flawless visual evoked potential SNR. Communication pathway fully established.',
    prescribedProtocolAdherence: 100,
  }
];

export const INITIAL_INTENTS: BCIIntentEvent[] = [
  {
    id: 'EVT-01',
    patientId: 'NP-101',
    timestamp: '11:58:32 AM',
    intent: "Spelled: 'THANK YOU'",
    category: 'speller',
    confidence: 0.96,
    eegFeatures: {
      muErdPct: -32,
      betaPeakHz: 18.5,
      p300LatencyMs: 310,
      targetElectrode: 'Pz'
    },
    executedAction: 'TTS Audio Output Broadcast: "Thank you"',
    status: 'executed'
  },
  {
    id: 'EVT-02',
    patientId: 'NP-101',
    timestamp: '11:45:10 AM',
    intent: 'Nurse Call / Suction Request',
    category: 'assistive_alert',
    confidence: 0.98,
    eegFeatures: {
      muErdPct: -48,
      betaPeakHz: 21.0,
      p300LatencyMs: 295,
      targetElectrode: 'Cz'
    },
    executedAction: 'ICU Central Nursing Station Alert Triggered (Bay 4A)',
    status: 'executed'
  },
  {
    id: 'EVT-03',
    patientId: 'NP-102',
    timestamp: '11:32:04 AM',
    intent: 'Robotic Hand Flexion & Power Grip',
    category: 'motor_imagery',
    confidence: 0.91,
    eegFeatures: {
      muErdPct: -54,
      betaPeakHz: 19.8,
      p300LatencyMs: 330,
      targetElectrode: 'C3'
    },
    executedAction: 'FES + Exoskeleton closing right hand around object',
    status: 'executed'
  },
  {
    id: 'EVT-04',
    patientId: 'NP-103',
    timestamp: '09:22:15 AM',
    intent: 'Virtual Reality Target Reach (Right Arm)',
    category: 'motor_imagery',
    confidence: 0.86,
    eegFeatures: {
      muErdPct: -38,
      betaPeakHz: 22.4,
      p300LatencyMs: 350,
      targetElectrode: 'C4'
    },
    executedAction: 'VR avatar executed forward arm extension animation',
    status: 'verified'
  },
  {
    id: 'EVT-05',
    patientId: 'NP-104',
    timestamp: '10:12:45 AM',
    intent: 'SSVEP Selection: "Need Water / Oral Care"',
    category: 'speller',
    confidence: 0.97,
    eegFeatures: {
      muErdPct: -22,
      betaPeakHz: 15.0,
      p300LatencyMs: 300,
      targetElectrode: 'Oz'
    },
    executedAction: 'Bedside Tablet Displayed Oral Swab Request to Caregiver',
    status: 'executed'
  }
];

export const INITIAL_BOOKINGS: AppointmentBooking[] = [
  {
    id: 'book-seed-1',
    userId: 'seed-patient-elena',
    userEmail: 'elena.patient@neuropulse.org',
    userName: 'Elena Rostova (Patient)',
    patientId: 'NP-102',
    patientName: 'Elena Rostova',
    doctorName: 'Dr. Sarah Jenkins, MD',
    specialty: 'Physical Medicine & Rehabilitation',
    appointmentDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    appointmentTime: '10:30 AM',
    sessionType: 'SMR Hand Grasp Neurofeedback + FES',
    contactPhone: '+1 (555) 489-2104',
    clinicalNotes: 'Check mu-rhythm suppression over C3/C4 sensorimotor cortex with robotic hand orthosis.',
    urgency: 'routine',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'book-seed-2',
    userId: 'seed-caregiver-david',
    userEmail: 'caregiver.david@neuropulse.org',
    userName: 'David Vance (Caregiver)',
    patientId: 'NP-101',
    patientName: 'Marcus Vance',
    doctorName: 'Dr. Riley Chen, MD, PhD',
    specialty: 'Chief Neurotechnologist & Clinical Director',
    appointmentDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    appointmentTime: '02:00 PM',
    sessionType: 'P300 Matrix Speller Calibration',
    contactPhone: '+1 (555) 234-9812',
    clinicalNotes: 'Recalibrate P300 flash duration for 6x6 spelling grid. Caregiver requesting alphabet speed boost.',
    urgency: 'priority',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'book-seed-3',
    userId: 'seed-patient-mateo',
    userEmail: 'mateo.silva@neuropulse.org',
    userName: 'Mateo Silva (Patient)',
    patientId: 'NP-103',
    patientName: 'Mateo Silva',
    doctorName: 'Dr. Aaron Patel, MD',
    specialty: 'Neuro-ICU & Critical Care Neurologist',
    appointmentDate: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
    appointmentTime: '09:00 AM',
    sessionType: 'Motor Imagery Robotic Exoskeleton Sync',
    contactPhone: '+1 (555) 782-9901',
    clinicalNotes: 'Post-stroke hemiplegia bilateral beta wave desynchronization assessment.',
    urgency: 'routine',
    status: 'confirmed',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  }
];
